apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-issuer-loki-grafana
  namespace: loki
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: mickaelpatrickranivo@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cert-manager-issuer-loki-grafana-secret
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
