# tasks file for roles/init_masters
## Kubeadm init server
- name: Copy azure.json file with owner and permissions
  become: true
  ansible.builtin.template:
    src: azure.json.j2
    dest: /etc/kubernetes/azure.json
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Copy kubeadm_config file with owner and permissions
  ansible.builtin.copy:
    src: "{{ role_path }}/files/kubeadm_config.yaml"
    dest: /home/{{ ansible_user }}/kubeadm_config.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Initializing Kubernetes Cluster
  become: true
  command: kubeadm init --config=/home/{{ ansible_user }}/kubeadm_config.yaml
  run_once: true

- pause: seconds=30

- name: Create directory for kube config.
  become: true
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy /etc/kubernetes/admin.conf to user home directory /home/{{ ansible_user }}/.kube/config.
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Get the token for joining the nodes with Kuberentes master.
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }} --cri-socket=unix:///var/run/cri-dockerd.sock" dest="/tmp/kubernetes_join_command" mode=0777

- name: Copy the cluster config
  become: true
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/config
    flat: yes
