apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-service-hpa
  namespace: sample-app-kub-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85 