# tasks file for roles/worker_join
### Kubeadm join worker
- name: Copy join command to worker nodes.
  become: true
  copy:
    src: /tmp/kubernetes_join_command
    dest: /home/{{ ansible_user }}/kubernetes_join_command
    mode: 0777

- name: Join the Worker nodes with the master.
  become: true
  command: sh /home/{{ ansible_user }}/kubernetes_join_command
  register: joined_or_not

- debug:
    msg: "{{ joined_or_not.stdout }}"

- name: Create directory for kube config.
  become: true
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy the config file
  become: true
  copy:
    src: /tmp/config
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: false
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
