name: Tests

on:
    push:
        branches:
            - develop

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.18
                  cache-dependency-path: app/backend/go.sum

            - name: Install dependencies
              run: go get .
              working-directory: app/backend
            
            - name: Build
              working-directory: app/backend
              run: go build -v ./...  

            - name: Run tests
              run: go test 
              working-directory: app/backend

