apiVersion: v1
kind: Secret
metadata:
  name: dex-secret
  namespace: dex
type: Opaque
data:
  GITHUB_CLIENT_ID: T3YyM2xpcWNFT3ZNcmhaY0Jsd1I=
  GITHUB_CLIENT_SECRET: N2UzNTg1YmUxOWNmZTczNTY5OTJhMmFmNjk2MDVlNWI4YjU1ZDdjNA==
